// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPlcvjvijkcBPoVaByb1a5Wye3fC7PtMI',
    appId: '1:41394169133:web:fbc7f2077811d018ffdfa4',
    messagingSenderId: '41394169133',
    projectId: 'personalapp-b6dee',
    authDomain: 'personalapp-b6dee.firebaseapp.com',
    storageBucket: 'personalapp-b6dee.firebasestorage.app',
    measurementId: 'G-26BS4RH606',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZD3R4yHeayu4sMXqaMIj4nlQCTP7wxzQ',
    appId: '1:41394169133:android:c371d2f908d39becffdfa4',
    messagingSenderId: '41394169133',
    projectId: 'personalapp-b6dee',
    storageBucket: 'personalapp-b6dee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdH0Tk577av3Uo5Ss1BxJsD8G1YnBMIp4',
    appId: '1:41394169133:ios:e8674e5c326943eeffdfa4',
    messagingSenderId: '41394169133',
    projectId: 'personalapp-b6dee',
    storageBucket: 'personalapp-b6dee.firebasestorage.app',
    iosBundleId: 'com.example.personalApplication',
  );

}